### ISSUE TITLE
Nginx support

### ISSUE THREAD

**Issue by natanfelles** [thiiagoms/phost#5]
Hi, @thiiagoms !

Very thanks for this awesome project.

Maybe would be good to have support for nginx.

Some time ago I writed this script: https://gist.github.com/natanfelles/903498837e82669b3285c31b79bae7ec

I believe would be good have nginx support in PHost.

If you have a little time, please check https://github.com/aplus-framework/cli
Maybe this library could help with CLI interactions, it is very customizable.

Thank you very much!

**Comment by thiiagoms** [comment]
Thank you so much!! I'll work on it for add support to nginx with aplus ❤️ 😍
